<?php
$data = $this->getProduct();
?>
<div class="container">
    <h2>Add New Product</h2>
    <form action="<?php echo $this->getUrl('admin/catalog_product/save') ?>" method="POST">
        <input type="hidden" value= "<?php echo $data->getProductId() ?>" id="sku" name="catalog_product[product_id]" >
        <label for="sku">SKU:</label>
        <input type="text" value= "<?php echo $data->getSku() ?>" id="sku" name="catalog_product[sku]" >

        <label for="name">Name:</label>
        <input type="text" value= "<?php echo $data->getName() ?>" id="name" name="catalog_product[name]" >
        
        <label for="color">Color:</label>
        <input type="text" value= "<?php echo $data->getColor() ?>" id="color" name="catalog_product[color]">
        
        <label for="size">Size:</label>
        <input type="text" value= "<?php echo $data->getSize() ?>" id="size" name="catalog_product[size]">
        
        <label for="description">Description:</label>
        <textarea id="description" name="catalog_product[description]"><?php echo $data->getDescription() ?> </textarea>
        
        <label for="image_link">Image Link:</label>
        <input type="text" value= "<?php echo $data->getImageLink() ?>" id="image_link" name="catalog_product[image_link]">
        
        <label for="link">Link:</label>
        <input type="text" value= "<?php echo $data->getLink() ?>" id="link" name="catalog_product[link]">
        
        <label for="category_id">Category ID:</label>
        <input type="number" value= "<?php echo $data->getCategoryId() ?>" id="category_id" name="catalog_product[category_id]" >
        
        <label for="price">Price:</label>
        <input type="text" value= "<?php echo $data->getPrice() ?>" id="price" name="catalog_product[price]" >
        
        <label for="mfr_cost">Manufacturer Cost:</label>
        <input type="text" value= "<?php echo $data->getMfrCost() ?>" id="mfr_cost" name="catalog_product[mfr_cost]">
        
        <label for="shipping_cost">Shipping Cost:</label>
        <input type="text" value= "<?php echo $data->getShippingCost() ?>" id="shipping_cost" name="catalog_product[shipping_cost]">
        
        <label for="total_cost">Total Cost:</label>
        <input type="text" value= "<?php echo $data->getTotalCost() ?>" id="total_cost" name="catalog_product[total_cost]">
        
        <label for="margin_percentage">Margin Percentage:</label>
        <input type="text" value= "<?php echo $data->getMarginPercentage() ?>" id="margin_percentage" name="catalog_product[margin_percentage]">
        
        <label for="min_price">Minimum Price:</label>
        <input type="text" value= "<?php echo $data->getMinPrice() ?>" id="min_price" name="catalog_product[min_price]">
        
        <label for="status">Status:</label>
        <input type="number" value= "<?php echo $data->getStatus() ?>" id="status" name="catalog_product[status]" >
        
        <input type="submit" value="Submit">
    </form>
</div>
