<?php
$productModel = Mage::getModel("catalog/product")->getCollection();
// $productModel->addFieldToFilter('name', 'abc');
// $productModel->addFieldToFilter('product_id', ['in'=>[52,53,54]]);
// $productModel->addFieldToFilter('sku', ['like'=>'%abc']);
// foreach ($productModel->getData() as $product) {
//     // echo get_class($product);
//     echo "<pre>";
//     print_r($product);
//     echo "<br>";
// }
?>

<div class="list">
    <h2>Product List</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>SKU</th>
                <th>Status</th>
                <th>Color</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($productModel->getData() as $_product): ?>
                        <tr>
                            <td>
                                <?php echo $_product->getName() ?>
                            </td>
                            <td>
                                <?php echo $_product->getSku() ?>
                            </td>
                            <td>
                                <?php echo $_product->getStatus() ?>
                            </td>
                            <td>
                                <?php echo $_product->getColor() ?>
                            </td>
                            <td>
                            <form action="<?php echo $this->getUrl('admin/catalog_product/delete') ?>" method="post" style="display: inline;">
                                <input type="hidden" name="product_id" value="<?php echo $_product->getId() ?>">
                                <button type="submit" class="delete-button">Delete</button>
                            </form>
                            </td>
                            <td>
                                <form action="<?php echo $this->getUrl('admin/catalog_product/form') ?>" method="get" style="display: inline;">
                                    <input type="hidden" name="product_id" value="<?php echo $_product->getId() ?>">
                                    <button type="submit" class="update-button">Update</button>
                                </form>
                            </td>

                        </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>