<?php
$data = $this->getProductList()->getData();
// echo "<pre>";
// print_r($data);
?>

<div>
    <h2>Catalog Product Fields</h2>
    <table>
        <tr>
            <th>product_id</th>
            <th>sku</th>
            <th>name</th>
            <th>color</th>
            <th>size</th>
            <th>description</th>
            <th>image_link</th>
            <th>link</th>
            <th>category_id</th>
            <th>price</th>
            <th>mfr_cost</th>
            <th>shipping_cost</th>
            <th>total_cost</th>
            <th>margin_percentage</th>
            <th>min_price</th>
            <th>status</th>
        </tr>
    <?php foreach ($data as $_data): ?>
        <tr>
            <td class="row_data"><?php echo $_data['product_id']; ?></td>
            <td class="row_data"><?php echo $_data['sku']; ?></td>
            <td class="row_data"><?php echo $_data['name'] ?></td>
            <td class="row_data"><?php echo $_data['color'] ?></td>
            <td class="row_data"><?php echo $_data['size'] ?></td>
            <td class="row_data"><?php echo $_data['description'] ?></td>
            <td class="row_data"><?php echo $_data['image_link'] ?></td>
            <td class="row_data"><?php echo $_data['link'] ?></td>
            <td class="row_data"><?php echo $_data['category_id'] ?></td>
            <td class="row_data"><?php echo $_data['price'] ?></td>
            <td class="row_data"><?php echo $_data['mfr_cost'] ?></td>
            <td class="row_data"><?php echo $_data['shipping_cost'] ?></td>
            <td class="row_data"><?php echo $_data['total_cost'] ?></td>
            <td class="row_data"><?php echo $_data['margin_percentage'] ?></td>
            <td class="row_data"><?php echo $_data['min_price'] ?></td>
            <td class="row_data"><?php echo $_data['status'] ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>
