<?php

// $productId = $this->getRequest()->getParams('id');
// $productModel = Mage::getModel('catalog/product')->load(5);
// echo "<pre>";
// print_r($productModel->getId() . PHP_EOL);
// print_r($productModel->getProductName() . PHP_EOL);
// print_r($productModel->getSku() . PHP_EOL);
// print_r($productModel->getProductType() . PHP_EOL);
// print_r($productModel->getCatId() . PHP_EOL);
// print_r($productModel->getManufacturerCost() . PHP_EOL);
// print_r($productModel->getShippingCost() . PHP_EOL);
// print_r($productModel->getTotalCost() . PHP_EOL);
// print_r($productModel->getPrice() . PHP_EOL);
// print_r($productModel->getStatus() . PHP_EOL);
// print_r($productModel->getCreatedAt() . PHP_EOL);
// print_r($productModel->getUpdatedAt() . PHP_EOL);
// print_r($productModel);

echo $this->getChildHtml("form");