<footer>
    <div>
        <div class="footerSection-1">
            <div class="footerItem">
                <p class="footerHeading">About Us</p>
                <p>Hello My name is Mohit Dodeja</p>
                <p>Secure Online Payments</p>
            </div>
            <div class="footerItem">
                <p class="footerHeading">Informations</p>
                <ul>
                    <li><a href="#">About Us</a></li>
                    <li><a href="mailto:mohitdodeja1992@gmail.com">Contact Us</a></li>
                    <li><a href="#">Return & Exchange</a></li>
                    <li><a href="#">Shipping & Delivery</a></li>
                    <li><a href="#">Term & Condition</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="footerItem">
                <p class="footerHeading">Contact Us</p>
            </div>
        </div>
        <div class="footerSection-2">
            <p>Copyright &#169; 2024 All rights reserved and made with &#9829; by Online Marketplace Platform(MD)</p>
        </div>
    </div>

</footer>