<!-- <?php
// $_product = $this->getSingleProduct();
?>
<form action="<?php #echo $this->getUrl('sales/quote/add')   ?>" method="post">
    <div class="product-page">
        <div class="product-image">
            <img src="product.jpg" alt="Product">
        </div>
        <div class="product-info">
            <h1>
                <?php #echo $_product->getName()   ?>
            </h1>
            <p>
                <?php #echo $_product->getDescription()   ?>
            </p>
            <p>
                <?php #echo "&#8377;" . $_product->getPrice()   ?>
            </p>
            <div class="quantity">
                <label for="quantity">Quantity:</label>
                <input type="hidden" name="sales_quote[product_id]" value="<?php #echo $_product->getId()   ?>">
                <input type="hidden" name="sales_quote[price]" value="<?php #echo $_product->getPrice()   ?>">
                <input type="number" id="quantity" name="sales_quote[qty]" min="1" value="1">
            </div>
            <input type="submit" name="submit" value="Add to Cart" class="add-to-cart">
        </div>
    </div>
</form> -->

<table border="1px">
    <tr>
        <th>Product Id</th>
        <th>Image</th>
        <th>Name</th>
        <th>Color</th>
        <th>Description</th>
        <th colspan=2>AddTocart</th>
    </tr>
    <?php foreach ($this->getItem() as $product) { ?>
        <tr>
            <td>
                <?php echo $product->getProductId(); ?>
            </td>
            <td>
                <img src="<?php echo Mage::getBaseUrl('media/product/') . $product->getImageLink(); ?>" style="width:200px" alt=""> 
            </td>
            <td>
                <?php echo $product->getName(); ?>
            </td>
            <td>
                <?php echo $product->getColor(); ?>
            </td>
            <td>
                <?php echo $product->getDescription(); ?>
            </td>
            <form method="POST" action="<?php echo $this->getUrl('sales/quote/add') ?>">
                <td>
                    <div class="form">
                        <?php //$categoryModel = $this->getCategoryForm();   ?>
                        <div class="row">
                            <input type="hidden" name="sales_quote[product_id]" value="<?php echo $product->getProductId(); ?>">
                        </div>
                        <div class="row">
                            <label for="quentity">Quantity : </label>
                            <input type="text" name="sales_quote[qty]" id="quentity"
                                value="<?php //echo $product->getQuentity();   ?>">
                        </div>
                    </div>
                </td>
                <td>
                    <div class="row">
                        <input type="submit" value="AddToCart">
                    </div>
                </td>
            </form>
        </tr>
    <?php } ?>
</table>
